name: First Job Patryk Wozniak
on: [push]
jobs:
  Test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check python version
        uses: actions/checkout@v3
