name: Check version
on: [push]
jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check python version
        uses: actions/checkout@v3     
  check_pylint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pylint
      - run: find . -type f -name "*.py" | xargs pylint 
      - name: Check pylint
        uses: actions/checkout@v3
    

