name: Check version
on: [push]
jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check python version
        uses: actions/checkout@v3     
  check_pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check pylint code
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Test app.py
        run: pylint app.py
  build_docker:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: BuildX
      uses: docker/setup-buildx-action@v1
    - name: Build docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: test-flask-app
    

