name: Check version
on: [push]
jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check python version
        uses: actions/checkout@v3     
  check_pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check pylint code
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install pylint
      - name: Test app.py
        run: pylint app.py
  build_docker:
    runs-on: ubuntu-latest
    steps: 
      - run: docker build .
      - name: docker/build-push-action@v2
        uses: actions/checkout@v3
    

