name: First Job Patryk Wozniak
on: [push]
jobs:
  Test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sprawdzanie zmian"
      - run: git status
      - run: git pull
        uses: actions/checkout@v3
