name: Check version
on: [push]
jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check python version
        uses: actions/checkout@v3     
  check_pylint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pylint
      - run: pylint app.py
      - name: Check pylint
        uses: actions/checkout@v3
  build_docker:
    runs-on: ubuntu-latest
    steps: 
      - run: docker build --tag test-flask-app .
      - name: Build docker image
        uses: actions/checkout@v3
    

